name: Maven CI/CD to Tomcat 9

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package --file pom.xml

    - name: Deploy WAR to Tomcat 9
      env:
        TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
      run: |
        WAR_FILE=$(find . -name "*.war" | head -n 1)
        echo "Deploying $WAR_FILE to Tomcat..."
        curl -u $TOMCAT_USER:$TOMCAT_PASSWORD \
             -T "$WAR_FILE" \
             "http://3.136.108.116:8081/manager/text/deploy?path=/project&update=true"
